In [3]:
import pandas as pd
import numpy as np

In [4]:
data=pd.Series(np.arange(10,101,10))
data

0     10
1     20
2     30
3     40
4     50
5     60
6     70
7     80
8     90
9    100
dtype: int64

In [5]:
type(data)

pandas.core.series.Series

In [7]:
data={'a':1,'b':2,'c':3}
dict_series=pd.Series(data)
print(dict_series)

a    1
b    2
c    3
dtype: int64

In [8]:
data=[10,20,30]
index=['a','b','c']
series=pd.Series(data,index=index)
series

a    10
b    20
c    30
dtype: int64

# DATAFRAME

In [10]:
DATA={
    'names':['FAIROZ','SAMEER','HUSSAIN','ABID'],
    'roll':[1,2,3,4],
    'age':[21,22,21,10]
}

df=pd.DataFrame(data=DATA)

In [12]:
df

     names  roll  age
0   FAIROZ     1   21
1   SAMEER     2   22
2  HUSSAIN     3   21
3     ABID     4   10

In [13]:
# Creating Dataframe from the list of  dictionaries

data=[
    {'name':"fairoz",'age':21,'roll':1},
    {'name':"sameer",'age':22,'roll':2},
    {'name':"hussain",'age':21,'roll':3},
    {'name':"abid",'age':8,'roll':4},
]

data_f=pd.DataFrame(data=data)

In [14]:
data_f

      name  age  roll
0   fairoz   21     1
1   sameer   22     2
2  hussain   21     3
3     abid    8     4